### ISSUE TITLE
Running CLI throws error due to ndebug

### ISSUE THREAD

**Issue by fhchl** [relekang/python-semantic-release#133]
Not sure if this is a bug in semantic-release error or ndbug. On my environment, running the CLI throws the following error

```
> semantic-release                                                                                                            master
Traceback (most recent call last):
  File "/home/fhchl/miniconda3/envs/sfc/bin/semantic-release", line 6, in <module>
    from semantic_release.cli import main
  File "/home/fhchl/miniconda3/envs/sfc/lib/python3.7/site-packages/semantic_release/cli.py", line 7, in <module>
    import ndebug
  File "/home/fhchl/miniconda3/envs/sfc/lib/python3.7/site-packages/ndebug/__init__.py", line 11, in <module>
    from .lib import create, enable  # noqa: F401
  File "/home/fhchl/miniconda3/envs/sfc/lib/python3.7/site-packages/ndebug/lib.py", line 20, in <module>
    options = env_helpers.options()
  File "/home/fhchl/miniconda3/envs/sfc/lib/python3.7/site-packages/ndebug/env_helpers.py", line 31, in options
    obj[prop] = int(val, 10)
ValueError: invalid literal for int() with base 10: '-D_DEBUG -D_FORTIFY_SOURCE=2 -Og'
```

This comes from having the environment variable `DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og` set.

**Comment by relekang** [comment]
This looks like a problem with ndebug. Feel free to reopen if you find something we need to change.
