### ISSUE TITLE
SyntaxError when trying to run python-semantic-release

### ISSUE THREAD

**Issue by MarkHedleyJones** [relekang/python-semantic-release#138]
Hi,
First, thanks for the project!
I'm trying to add versioning to a project of mine and your project looks perfect for the job.

Here are my details:
I'm running Ubuntu 16.04.
I've tried installing this via pip and later via pip3 (not simultaniously).
I get the following output whenever I run `semantic-release`
```
Traceback (most recent call last):
  File "/usr/local/bin/semantic-release", line 6, in <module>
    from semantic_release.cli import main
  File "/usr/local/lib/python3.5/dist-packages/semantic_release/cli.py", line 12, in <module>
    from .history import (evaluate_version_bump, get_current_version, get_new_version,
  File "/usr/local/lib/python3.5/dist-packages/semantic_release/history/__init__.py", line 12, in <module>
    from .logs import evaluate_version_bump  # noqa
  File "/usr/local/lib/python3.5/dist-packages/semantic_release/history/logs.py", line 76
    changes: dict = {'feature': [], 'fix': [],
           ^
SyntaxError: invalid syntax
```

It doesn't matter what arguments I supply, the result is the same.
Any ideas?

**Comment by relekang** [comment]
In v4 we added type hints. Python 3.6 is the first version to support the type hints syntax. Please either use v3.x of python-semantic-release or python 3.6+.
