### ISSUE TITLE
pyproject.toml not working

### ISSUE THREAD

**Issue by danth** [relekang/python-semantic-release#235]
## The problem

Settings in `pyproject.toml` are not loaded:

```
error: No option 'version_variable' in section: 'semantic_release'
```

## Expected behavior

Settings are loaded from `pyproject.toml` if it exists.

## Additional context

The problematic repo doesn't have a `setup.cfg` file at all.

**Comment by lcnittl** [comment]
For the use in `pyproject.toml`, you have to use the `[tool.semantic_release]` section (`tool` prepended).

Hope this helps!

**Comment by derfabianpeter** [comment]
I have this in my `pyproject.toml`:

```
[tool.semantic_release]
version_variable = backplane/__init__.py:__version__
branch = master
build_command = poetry build
upload_to_release = true
upload_to_pypi = true
changelog_file = CHANGELOG.md
```

Nevertheless, calling `semantic-release -v DEBUG` always returns:

```
Creating new version
debug: get_current_version_by_config_file()
error: must specify either 'version_variable' or 'version_pattern'
```

**Comment by browniebroke** [comment]
Works fine for me. Did you see my comment here: https://github.com/relekang/python-semantic-release/issues/222#issuecomment-709326972

**Comment by derfabianpeter** [comment]
Thanks for pointing me there, but I believe my problem rather is that `semantic-release` doesn't even load or look for `pyproject.toml`.

**Comment by derfabianpeter** [comment]
Nevermind. It's a formatting error in `pyproject.toml`. Error handling is a bit confusing

**Comment by ygworldr** [comment]
I have the same problem here. Here is my `pyproject.toml` file with nothing omitted:

```toml
# -*- coding: utf-8 -*-

#   ____________
#__/ Town crier \_______________________________________________________________
#
[tool.towncrier]
directory = "changes"
filename = "NEWS.rst"

#   __________________
#__/ Semantic release \_________________________________________________________
#
# https://python-semantic-release.readthedocs.io/en/latest/
[tool.semantic_release]
version_pattern = [
    "README.md:VERSION {version}",
    "VERSION.txt:VERSION {version}",
]
version_source = tag
check_build_status = true
branch = main
changelog_file = CHANGELOG.md
```

And here is the debug logging:
```
√ (main ↑2|+2…1); semantic-release -v DEBUG changelog
debug: Main args:
--- Logging error ---
Traceback (most recent call last):
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click_log/core.py", line 51, in emit
    msg = self.format(record)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click_log/core.py", line 37, in format
    msg = record.getMessage()
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/yann/.pyenv/versions/3.8.6/bin/semantic-release", line 8, in <module>
    sys.exit(entry())
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/semantic_release/cli.py", line 320, in entry
    main(args=ARGS)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/semantic_release/settings.py", line 129, in wrap
    return func(*args, **kwargs)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/semantic_release/cli.py", line 337, in main
    logger.debug("Environment:", filter_output_for_secrets(message))
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/logging/__init__.py", line 1422, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/yann/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click_log/core.py", line 55, in emit
    self.handleError(record)
Message: 'Environment:'
Arguments: ('PYPI_USERNAME="None",PYPI_PASSWORD="None",GH_TOKEN="None",GL_TOKEN="None",',)
debug: Main config:
error: must specify either 'version_variable' or 'version_pattern'
```

**Comment by ygworldr** [comment]
Line 337 in `cli.py` reads:

```python
logger.debug("Environment:", filter_output_for_secrets(message))
```

which is wrong. It should read:

```python
logger.debug("Environment: %s", filter_output_for_secrets(message))
```

It does not solve my problem but at least I do not get an ugly trace…

**Comment by ygworldr** [comment]
The toml file is badly formatted. These are the correct changes:

```
version_source = "tag"
check_build_status = true
branch = "main"
changelog_file = "CHANGELOG.md"
```

The parsing fails but the errors are not reported. In `settings.py`, line 70 has a call to `logger.debug` which never appears on screen since logger is a `<Logger semantic_release.settings (WARNING)>` so anything below warning gets ignored. The code should read:

```python
    except toml.TomlDecodeError as err:
        logger.error("Could not decode pyproject.toml: %s", err)
        return {}
```

Do you want me to create a PR for those chances or are they trivial enough?

**Comment by relekang** [comment]
A PR would be welcome 👍
