### ISSUE TITLE
Tagging fails if the .git directory is in a different location to setup.py and setup.cfg

### ISSUE THREAD

**Issue by salimfadhley** [relekang/python-semantic-release#66]
I have a project in which the root directory contains src and src contains setup.py and setup.cfg.

When I run a semantic-release operation I get the following crash:
```

venv) C:\workspace\checklive\src>semantic-release --patch publish
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\workspace\checklive\venv\Scripts\semantic-release.exe\__main__.py", line 5, in <module>
  File "c:\workspace\checklive\venv\lib\site-packages\semantic_release\cli.py", line 9, in <module>
    from .history import (evaluate_version_bump, get_current_version, get_new_version,
  File "c:\workspace\checklive\venv\lib\site-packages\semantic_release\history\__init__.py", line 6, in <module>
    from ..vcs_helpers import get_commit_log, get_last_version
  File "c:\workspace\checklive\venv\lib\site-packages\semantic_release\vcs_helpers.py", line 8, in <module>
    repo = Repo('.git', search_parent_directories=True)
  File "c:\workspace\checklive\venv\lib\site-packages\git\repo\base.py", line 135, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: C:\workspace\checklive\src\.git

(venv) C:\workspace\checklive\src>
```

**Comment by relekang** [comment]
Thanks for reporting

**Comment by splendido** [comment]
I need some more time to confirm the following, but I'd say this could be fixed by changing [this lines](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/vcs_helpers.py#L8-L11) with these:

```python
try:
    repo = Repo('.', search_parent_directories=True)
except NoSuchPathError:
    raise RuntimeError("Not in a valid git repository")
```

**Comment by splendido** [comment]
See https://github.com/relekang/python-semantic-release/pull/89
